import Autoload from './shared/js/autoload';
import Base from './shared/js/base';
import Common from './shared/js/common';
import Jquery_min from './shared/js/jquery.min.js';
import Jquery_rss from './shared/js/jquery.rss.js';
import Remodal from './shared/js/remodal';
import Shared from './shared/js/shared';
import Slick from './shared/js/slick';
import Viewport from './shared/js/viewport';
import Wow from './shared/js/wow.min.js';

const autoload = new Autoload();
const base = new Base();
const common = new Common();
const jquery_min = new Jquery_min();
const jquery_rss = new Jquery_rss();
const remodal = new Remodal();
const shared = new Shared();
const slick = new Slick();
const viewport = new Viewport();
const wow = new Wow();